In [1]:
#Which location having maximum death cases for male and female and Print all types of symptom.
import pandas as pd
entiredf=pd.read_csv("COVID1.csv")

In [2]:
df=entiredf.copy()
df.head()
df.tail()

,id,case_in_country,reporting date,Unnamed: 3,summary,location,country,gender,age,symptom_onset,...,recovered,symptom,source,link,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
1080,1081,2.0,2/25/2020,NaN,"new COVID-19 patient confirmed in Austria: 24,...",Innsbruck,Austria,NaN,24.0,NaN,...,0,NaN,Jakarta Post,https://www.thejakartapost.com/news/2020/02/25...,NaN,NaN,NaN,NaN,NaN,NaN
1081,1082,1.0,2/24/2020,NaN,new COVID-19 patient confirmed in Afghanistan:...,Afghanistan,Afghanistan,NaN,35.0,NaN,...,0,NaN,Fox News,https://www.foxnews.com/health/afghanistan-fir...,NaN,NaN,NaN,NaN,NaN,NaN
1082,1083,1.0,2/26/2020,NaN,new COVID-19 patient confirmed in Algeria: mal...,Algeria,Algeria,male,NaN,NaN,...,0,NaN,South China Morning Post,https://www.scmp.com/news/china/society/articl...,NaN,NaN,NaN,NaN,NaN,NaN
1083,1084,1.0,2/25/2020,NaN,new COVID-19 patient confirmed in Croatia: mal...,Croatia,Croatia,male,NaN,NaN,...,0,NaN,Reuters,https://www.reuters.com/article/us-croatia-cor...,NaN,NaN,NaN,NaN,NaN,NaN
1084,1085,1.0,2/25/2020,NaN,new COVID-19 patient confirmed in Switzerland:...,Bern,Switzerland,male,70.0,2/17/2020,...,0,NaN,Reuters,https://www.reuters.com/article/uk-switzerland...,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(df.columns)
# last  columns are empty so dropping them
df=df.drop(['Unnamed: 3','Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26'],axis=1)

Index(['id', 'case_in_country', 'reporting date', 'Unnamed: 3', 'summary',
       'location', 'country', 'gender', 'age', 'symptom_onset',
       'If_onset_approximated', 'hosp_visit_date', 'exposure_start',
       'exposure_end', 'visiting Wuhan', 'from Wuhan', 'death', 'recovered',
       'symptom', 'source', 'link', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26'],
      dtype='object')

In [4]:

df.describe()

,id,case_in_country,age,If_onset_approximated,visiting Wuhan,from Wuhan
count,1085.000000,888.000000,843.000000,560.000000,1085.000000,1081.000000
mean,543.000000,48.841216,49.483689,0.042857,0.176959,0.144311
std,313.356825,78.853528,18.255334,0.202716,0.381810,0.351567
min,1.000000,1.000000,0.250000,0.000000,0.000000,0.000000
25%,272.000000,11.000000,35.000000,0.000000,0.000000,0.000000
50%,543.000000,28.000000,51.000000,0.000000,0.000000,0.000000
75%,814.000000,67.250000,64.000000,0.000000,0.000000,0.000000
max,1085.000000,1443.000000,96.000000,1.000000,1.000000,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1085 non-null   int64
 1   case_in_country        888 non-null    float64
 2   reporting date         1084 non-null   object
 3   summary                1080 non-null   object
 4   location               1085 non-null   object
 5   country                1085 non-null   object
 6   gender                 902 non-null    object
 7   age                    843 non-null    float64
 8   symptom_onset          563 non-null    object
 9   If_onset_approximated  560 non-null    float64
 10  hosp_visit_date        507 non-null    object
 11  exposure_start         128 non-null    object
 12  exposure_end           341 non-null    object
 13  visiting Wuhan         1085 non-null   int64
 14  from Wuhan             1081 non-null   float64
 15  death                  1085 non-null   object
 16  recovered              1085 non-null   object
 17  symptom                270 non-null    object
 18  source                 1085 non-null   object
 19  link                   1085 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 169.7+ KB

In [6]:
#Which  location  having maximum  death cases  for  --male and female ---  and Print all types of symptom.

# df.country.unique
print(df['death'].unique())
print()
print(entiredf['death'].unique())
# we have some entries with wrong formattings
print(df['death'].describe())
# gona drop those rows

['0' '1' '2/14/2020' '2/26/2020' '2/13/2020' '2/28/2020' '2/27/2020'
 '2/25/2020' '2/23/2020' '2/24/2020' '2/22/2020' '02/01/20' '2/19/2020'
 '2/21/2020']

['0' '1' '2/14/2020' '2/26/2020' '2/13/2020' '2/28/2020' '2/27/2020'
 '2/25/2020' '2/23/2020' '2/24/2020' '2/22/2020' '02/01/20' '2/19/2020'
 '2/21/2020']
count     1085
unique      14
top          0
freq      1022
Name: death, dtype: object

In [113]:
#['2/14/2020', '2/26/2020', '2/13/2020', '2/28/2020', '2/27/2020', '2/25/2020', '2/23/2020','2/24/2020', '2/22/2020', '02/01/20' ,'2/19/2020' , '2/21/2020']
#     df.drop(indexname,inplace=True)
df=df.loc[df.death.isin(['0','1'])]
df.gender=df.gender.astype(str)
df.gender.unique()
df=df.loc[df.gender.isin(['male','female'])]
df.gender.unique()
df.death=df.death.astype(int)

In [121]:
df_small=df[["location","gender","death"]]
print(df_small.death.sum())
# we now have the data grouped by province
df_small=df_small.groupby(["location","gender"])
df_small.head()
#df_small.sum().values
# pd.DataFrame(df_small).to_excel('smalldb.xlsx', sheet_name='new_sheet_name')

42

                 location  gender  death
0     Shenzhen, Guangdong    male      0
1                Shanghai  female      0
2                Zhejiang    male      0
3                 Tianjin  female      0
4                 Tianjin    male      0
...                   ...     ...    ...
1075              Bahrain    male      0
1076              Bahrain    male      0
1082              Algeria    male      0
1083              Croatia    male      0
1084                 Bern    male      0

[464 rows x 3 columns]

In [111]:
s=df_small
# find location with max  deaths
s.head()
# import pandas as pd
# import openpyxl
# s.to_excel('pandas_to_excel_no_index_header.xlsx', index=False, header=False)

In [84]:
# s.loc[s['death'].idxmax()]
print("Female max death location:")
print(s.xs('male',level='gender').idxmax().values)
print()
print("Male max death location:")
print(s.xs('female',level='gender').idxmax().values)

Female max death location:
['Wuhan, Hubei']

Male max death location:
['Wuhan, Hubei']

In [94]:
symptomps=df['symptom'].dropna()
#printing all simptomps
symptomps=list(symptomps)
symptomps
all_str=' '.join(str(e) for e in symptomps) # keeping all
res = tuple(map(str, all_str.split(', '))) 
res# printing the tuple

['feaver, cough, difficult in breathing',
 'feaver, cough, difficult in breathing',
 'fever',
 'fever',
 'fever',
 'cough, chills, joint pain',
 'fever, cough',
 'fever, cough',
 'throat pain, fever',
 'fever',
 'fever, cough',
 'fever',
 'fever, cough',
 'fever, runny nose',
 'fever, cough',
 'fever',
 'fever',
 'fever',
 'fever, cough',
 'fever',
 'fever, abdominal pain, diarrhea',
 'fever, cough',
 'cough, joint pain',
 'vomiting, diarrhea, fever, cough',
 'fever, loss of appetite',
 'fever',
 'fever, cough, malaise',
 'fever',
 'fever',
 'fever, cough',
 'fever, headache',
 'fatigue, difficulty breathing',
 'fever, malaise',
 'fever',
 'fever, malaise',
 'fever, malaise',
 'fever',
 'fever',
 'fever, vomiting, diarrhea',
 'fever',
 'fever',
 'fever',
 'fever, cough, sputum, malaise',
 'fever, cough',
 'fever',
 'fatigue, muscle pain, joint pain, fever',
 'fever, sore throat',
 'fever, breathlessness, malaise',
 'cough, malaise, shortness of breath',
 'cough, malaise, shortness of breath',
 'cough, sputum, dyspnea',
 'fever, malaise',
 'fever, pneumonia',
 'fever',
 'fever, malaise, diarrhea, cough',
 'fever',
 'fever',
 'fever',
 'fever',
 'fever',
 'fever, cough, sputum',
 'fever, cough, malaise',
 'fatigue',
 'fatigue, loss of appetite',
 'fever, cough',
 'fever, cough, breathlessness',
 'cough, fever, headache, nausea, vomiting, diarrhea',
 'cough, fever',
 'fatigue, cold, fever, vomiting',
 'fever, fatigue, cough, diarrhea',
 'nausea',
 'fatigue, joint pain, fever',
 'cough, sputum',
 'fever, cough, malaise',
 'fever',
 'fatigue, malaise, headache',
 'fever, sore throat, malaise',
 'sore throat, cough, fever',
 'fever, cough',
 'fever, nasal discharge, headache',
 'fever',
 'fever, cough, malaise',
 'fever',
 'fever',
 'fever',
 'fever, difficulty breathing',
 'fever',
 'fever, cough',
 'joint pain, muscle pain, cough, malaise',
 'fever, headache',
 'fever, sore throat',
 'fever, cough',
 'chills',
 'fever',
 'cough',
 'fever, respiratory distress',
 'fever, malaise',
 'fever, malaise',
 'fever, sore throat',
 'mild cough, sputum, throat discomfort',
 'cough, sneeze',
 'fever, chills, joint pain, heavy head',
 'fatigue, fever',
 'sore throat',
 'fever',
 'fever',
 'fever',
 'fever, cough',
 'fever, runny nose',
 'fever',
 'fever',
 'fever',
 'headache, fever, malaise',
 'sore throat, fever',
 'fever',
 'fever, malaise',
 'fever, cough',
 'fever, cough',
 'fever, cough, malaise',
 'throat discomfort, cough, chest pain',
 'fever, cough, sputum, dyspnea',
 'fever, cough, sputum, dyspnea',
 'fever, cough, sputum',
 'fever, thirst',
 'fever',
 'fever, cough, runny nose',
 'fever, cough, malaise',
 'fever, cough, sore throat, runny nose',
 'malaise, fever, headache',
 'throat pain, chills',
 'fever',
 'fever, headache, malaise',
 'fever, cough, sputum',
 'fever, cough, headache',
 'cough, malaise',
 'fever',
 'fatigue, fever',
 'sore throat, fever, joint pain, dyspnea',
 'vomiting, cough, fever, sore throat',
 'fever',
 'fever, cough',
 'fever, headache, malaise, joint pain',
 'fever, cough',
 'fever, cough',
 'cough, fever, joint pain',
 'cough, fever',
 'fever, malaise, sore throat',
 'cough, sore throat',
 'fever',
 'fever, cough, headache',
 'fever, cough, flu',
 'fever',
 'fever, sore throat, cough',
 'mild fever',
 'fever',
 'cough',
 'fever',
 'sore throat',
 'fever, cough, chills',
 'fever',
 'fever',
 'fever, sore throat',
 'fever',
 'fever',
 'high fever, chills, muscle pain',
 'fever, sore throat',
 'fever, chills, muscle cramps',
 'high fever, aching muscles',
 'cough',
 'headache',
 'sore body',
 'chills',
 'sore throat',
 'fever, cough, sore throat',
 'chest discomfort',
 'cough, chill, muscle pain',
 'fever',
 'fever, cough, shortness of breath',
 'fever',
 'flu symptoms',
 'cough',
 'fever, muscle aches',
 'fever',
 'fever',
 'cough',
 'cough, runny nose',
 'fever, cough, headache',
 'cough, chest pain',
 'fever, cough',
 'cough',
 'fever, chills, sore throat, runny nose, shortness of breath',
 'cough, shortness of breath',
 'fever, cough',
 'fever, cough',
 'fever, cough',
 'reflux',
 'throat discomfort',
 'physical discomfort',
 'throat discomfort',
 'cough, itchy throat',
 'fever, chills, sore throat, headache',
 'fever',
 'fever',
 'fever',
 'fever, coughing, muscle aches',
 'cough',
 'fever, cough',
 'cough, fever',
 'fever',
 'fever',
 'fever',
 'fever, headache, runny nose',
 'tired',
 'fever, cough',
 'fever, runny nose',
 'fever',
 'sore throat, chills, myalgias, fever, cough',
 'fever, cough',
 'fever',
 'fever, cough',
 'feve\\',
 'fever, cough',
 'fever',
 'fever',
 'fever',
 'cough',
 'cough, shortness of breath',
 'myalgia, fever',
 'fever',
 'fever, cough',
 'cough',
 'fever, myalgia, shortness of breath',
 'cough, runny nose, diarrhea',
 'fever',
 'cough, sore throat',
 'fever, cough, sore throat',
 'sore throat, fever, diarrhea',
 'cough, malaise',
 'fever, cough',
 'fever, cough',
 'fever, cough',
 'fever, cough',
 'cough, chills, shortness of breath, diarrhea',
 'fever',
 'cough, diarrhea, vomiting',
 'cough, fever, chills',
 'fever',
 'cough',
 'fever',
 'cough, shortness of breath',
 'fever, sore throat',
 'runny nose, cough',
 'fever, cough',
 'cough',
 'cough, sputum, sore throat',
 'fever',
 'runny nose',
 'fever, cough',
 'fever, cough',
 'cough with sputum',
 'cough',
 'fever',
 'sore throat, fever',
 'cough']

In [106]:
#WHICH SYMPTOM IS MORE IN COVID

all_str
all_str=all_str.replace(',',' ')
all_str=all_str.replace('sore throat','sore_throat ')
all_str=all_str.replace('runny nose','runny_nose')
all_str=all_str.replace('feve\\','fever')
from collections import Counter
split_it = all_str.split() 
Counter=Counter(split_it)
most_occuring = Counter.most_common(4)
most_occuring
#count no of wors

[('fever', 201), ('cough', 114), ('malaise', 28), ('sore_throat', 27)]